version: '3.3'

services:
  user:
    build:
     context: ./
     dockerfile: apps/user/Dockerfile
  matchmaking:
    build:
     context: ./
     dockerfile: apps/matchmaking/Dockerfile
  round:
    build:
     context: ./
     dockerfile: apps/round/Dockerfile
  stats:
    build:
     context: ./
     dockerfile: apps/stats/Dockerfile
    

