/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface PokemonApi {
	getPokemonsWithNumberOfMatchs: () => Promise<GetPokemonsWithNumberOfMatchsResponse>
	getNumberOfMatchsByPokemon: (id: number) => Promise<GetNumberOfMatchsByPokemonResponse>
	getNumberOfVictoriesByPokemon: (id: number) => Promise<GetNumberOfVictoriesByPokemonResponse>
}

export type GetPokemonsWithNumberOfMatchsResponse = GetPokemonsWithNumberOfMatchs200Response

export interface GetPokemonsWithNumberOfMatchs200Response {
	status: 200
	body: Api.ArrayOfPokemon[]
	headers?: never
}

export type GetNumberOfMatchsByPokemonResponse = GetNumberOfMatchsByPokemon200Response

export interface GetNumberOfMatchsByPokemon200Response {
	status: 200
	body: Api.GetNumberOfMatchsByPokemon200Response
	headers?: never
}

export type GetNumberOfVictoriesByPokemonResponse = GetNumberOfVictoriesByPokemon200Response

export interface GetNumberOfVictoriesByPokemon200Response {
	status: 200
	body: Api.GetNumberOfVictoriesByPokemon200Response
	headers?: never
}

