/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import match from './api/match'
import pokemon from './api/pokemon'
import * as t from './types'

export default function(app: Express, impl: t.ApiImplementation) {
	match(app, impl.match)
	pokemon(app, impl.pokemon)
}
