/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface ArrayOfMatch {
		/**
		 * <p>Date of the aggregated day</p>
		 * @type {string}
		 * @memberof ArrayOfMatch
		 */
		date?: string;
		/**
		 * <p>Date of matches for this day</p>
		 * @type {number}
		 * @memberof ArrayOfMatch
		 */
		numberOfMatches?: number;
	}

	export interface ArrayOfPokemon {
		/**
		 * <p>Pokemon&#39;s id</p>
		 * @type {number}
		 * @memberof ArrayOfPokemon
		 * minimum: 0
		 */
		id?: number;
		/**
		 * <p>Number of matchs for this pokemon</p>
		 * @type {number}
		 * @memberof ArrayOfPokemon
		 */
		numberOfMatchs?: number;
	}

	export interface GetNumberOfMatchsByPokemon200Response {
		/**
		 * <p>Pokemon&#39;s id used in the request</p>
		 * @type {number}
		 * @memberof GetNumberOfMatchsByPokemon200Response
		 */
		id?: number;
		/**
		 * <p>Number of matchs for this pokemon</p>
		 * @type {number}
		 * @memberof GetNumberOfMatchsByPokemon200Response
		 */
		numberOfMatchs?: number;
	}

	export interface GetNumberOfVictoriesByPokemon200Response {
		/**
		 * <p>Pokemon&#39;s id used in the request</p>
		 * @type {number}
		 * @memberof GetNumberOfVictoriesByPokemon200Response
		 * minimum: 0
		 */
		id?: number;
		/**
		 * <p>Number of victories for this pokemon</p>
		 * @type {number}
		 * @memberof GetNumberOfVictoriesByPokemon200Response
		 */
		numberOfVictories?: number;
	}

}
