/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import * as match from './api/match/types'
import * as pokemon from './api/pokemon/types'

export interface ApiImplementation {
	match: match.MatchApi
	pokemon: pokemon.PokemonApi
}
