/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from './models'

type FromJsonFunction<T> = (name: string, value: any) => T
type MapOf<T> = { [name: string]: T }

/**
 * A conditional type to convert an interface model to the equivalent JSON model.
 * We may represent dates as Date objects in our object model, but we must translate
 * them to strings for the JSON model.
 */
type ToJson<T> =
	T extends Date ? string
	: T extends object ? {
		[P in keyof T]: ToJson<T[P]>
	}
	: T extends (infer R)[] ? ToJson<R>[]
	: T

export function arrayFromJson<T>(next: FromJsonFunction<T>): FromJsonFunction<T[]> {
	return function(name: string, value: any) {
		if (typeof value !== 'object' || typeof value.length !== 'number') {
			throw `Invalid type for ${name}: expected array got ${typeof value}`
		}
	
		const result: T[] = []
		for (const el of value) {
			result.push(next(name, el))
		}
		return result
	}
}

export function arrayToJson<T>(next: FromJsonFunction<T>): FromJsonFunction<T[]> {
	return arrayFromJson(next)
}

export function mapFromJson<T>(next: FromJsonFunction<T>): FromJsonFunction<MapOf<T>> {
	return function(name: string, value: any) {
		if (typeof value !== 'object') {
			throw `Invalid type for ${name}: expected object got ${typeof value}`
		}
	
		const result: MapOf<T> = {}
		for (const key in value) {
			if (value.hasOwnProperty(key)) {
				result[key] = next(name, value[key])
			}
		}
		return result
	}
}

export function mapToJson<T>(next: FromJsonFunction<T>): FromJsonFunction<MapOf<T>> {
	return mapFromJson(next)
}

export function allowNull<T>(next: FromJsonFunction<T>): FromJsonFunction<T | null> {
	return function(name: string, value: any) {
		if (value === null) {
			return null
		}
		return next(name, value)
	}
}

export function allowUndefined<T>(next: FromJsonFunction<T>): FromJsonFunction<T | undefined> {
	return function(name: string, value: any) {
		if (value === undefined) {
			return undefined
		}
		return next(name, value)
	}
}

export function allowNullOrUndefined<T>(next: FromJsonFunction<T>): FromJsonFunction<T | null | undefined> {
	return function(name: string, value: any) {
		if (value === null) {
			return null
		}
		if (value === undefined) {
			return undefined
		}
		return next(name, value)
	}
}

export function unsupportedFromJson(name: string, value: any): unknown {
	if (value === undefined) {
		throw `Invalid type for ${name}: expected unknown got undefined`
	}
	return value
}

export function unsupportedToJson(name: string, value: unknown): any {
	return unsupportedFromJson(name, value)
}

export function parseUnsupported(name: string, value: any): unknown {
	if (value === undefined) {
		throw `Invalid value for ${name}: expected unknown got undefined`
	}
	return value
}

export function booleanFromJson(name: string, value: any): boolean {
	if (typeof value !== 'boolean') {
		throw `Invalid type for ${name}: expected boolean got ${typeof value}`
	}
	return value
}

export function booleanToJson(name: string, value: boolean): any {
	return booleanFromJson(name, value)
}

export function parseBoolean(name: string, value: any): boolean {
	if (value === 'true') {
		return true
	} else if (value === 'false') {
		return false
	} else {
		throw `Invalid value for ${name}: expected boolean got "${value}"`
	}
}

export function stringFromJson(name: string, value: any): string {
	if (typeof value !== 'string') {
		throw `Invalid type for ${name}: expected string got ${typeof value}`
	}
	return value
}

export function stringToJson(name: string, value: string): any {
	return stringFromJson(name, value)
}

export function binaryFromJson(name: string, value: any): Buffer {
	if (typeof value !== 'string') {
		throw `Invalid type for ${name}: expected string got ${typeof value}`
	}
	return new Buffer(value, 'base64')
}

export function binaryToJson(name: string, value: string | Buffer): string {
	if (typeof value === 'string') {
		return value
	} else {
		return value.toString('base64')
	}
}

export function parseString(name: string, value: any): string {
	if (value === undefined) {
		throw `Invalid value for ${name}: expected string got undefined`
	}
	if (typeof value === 'string') {
		return value
	}
	if (typeof value === 'object' && typeof value.length === 'number') {
		if (value.length > 0) {
			return value[0]
		}
	}

	throw `Invalid value for ${name}: expected string got ${typeof value}`
}

export function integerFromJson(name: string, value: any): number {
	if (typeof value !== 'number') {
		throw `Invalid type for ${name}: expected number got ${typeof value}`
	}
	if (isNaN(value)) {
		throw `Invalid NaN for ${name}`
	}
	if (Math.floor(value) !== value) {
		throw `Invalid value for ${name}: expected integer got "${value}"`
	}
	return value
}

export function integerToJson(name: string, value: number): any {
	return integerFromJson(name, value)
}

export function parseInteger(name: string, value: any): number {
	if (typeof value === 'object' && typeof value.length === 'number' && value.length > 0) {
		value = value[0]
	}
	if (typeof value === 'string') {
		if (value.indexOf('.') !== -1) {
			throw `Invalid value for ${name}: expected integer got "${value}"`
		}

		const result = parseInt(value, 10)
		if (isNaN(result)) {
			throw `Invalid value for ${name}: expected integer got "${value}"`
		}
		return result
	}
	throw `Invalid value for ${name}: expected integer got ${typeof value}`
}

export function numberFromJson(name: string, value: any): number {
	if (typeof value !== 'number') {
		throw `Invalid type for ${name}: expected number got ${typeof value}`
	}
	if (isNaN(value)) {
		throw `Invalid NaN for ${name}`
	}
	return value
}

export function numberToJson(name: string, value: number): any {
	return numberFromJson(name, value)
}

export function parseNumber(name: string, value: any): number {
	if (typeof value === 'object' && typeof value.length === 'number' && value.length > 0) {
		value = value[0]
	}
	if (typeof value === 'string') {
		const result = parseFloat(value)
		if (isNaN(result)) {
			throw `Invalid value for ${name}: expected float got "${value}"`
		}
		return result
	}
	throw `Invalid value for ${name}: expected number got ${typeof value}`
}

export function dateFromJson(name: string, value: any): string {
	if (typeof value !== 'string') {
		throw `Invalid type for ${name}: expected string got ${typeof value}`
	}
	if (!value.match(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/)) {
		throw `Invalid value for ${name}: expected valid date string got "${value}"`
	}
	return value
}

export function parseDate(name: string, value: any): string {
	return dateFromJson(name, value)
}

export function dateToJson(name: string, value: string): string {
	return dateFromJson(name, value)
}

export function dateTimeFromJson(name: string, value: any): Date {
	if (typeof value !== 'string') {
		throw `Invalid type for ${name}: expected string got ${typeof value}`
	}
	if (!value.match(/^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?(Z|(\+|-)[0-9]{2}(:?[0-9]{2})?)$/)) {
		throw `Invalid value for ${name}: expected valid datetime string got "${value}"`
	}
	return new Date(value)
}

export function parseDateTime(name: string, value: any): Date {
	return dateTimeFromJson(name, value)
}

export function dateTimeToJson(name: string, value: Date): string {
	if (typeof value !== 'object' || typeof value.toISOString !== 'function') {
		throw `Invalid type for ${name}: expected Date got ${typeof value}`
	}
	return value.toISOString()
}

export function timeFromJson(name: string, value: any): string {
	if (typeof value !== 'string') {
		throw `Invalid type for ${name}: expected string got ${typeof value}`
	}
	if (!value.match(/^[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?$/)) {
		throw `Invalid value for ${name}: expected valid time string got "${value}"`
	}
	return value
}

export function parseTime(name: string, value: any): string {
	return timeFromJson(name, value)
}

export function timeToJson(name: string, value: string): string {
	return timeFromJson(name, value)
}

/* Model conversion functions */

const ApiArrayOfMatchKeys: string[] = ['date', 'numberOfMatches']

function modelApiArrayOfMatchFromJsonContent(name: string, value: any, knownKeys: Record<string, boolean> = {}): Api.ArrayOfMatch {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiArrayOfMatchKeys.forEach(k => knownKeys[k] = true)

	const result: Api.ArrayOfMatch = {
		'date': allowUndefined(dateFromJson)(`${name}.date`, value['date']),
		'numberOfMatches': allowUndefined(integerFromJson)(`${name}.numberOfMatches`, value['numberOfMatches']),
	}

	return result
}

function modelApiArrayOfMatchToJsonContent(name: string, value: Api.ArrayOfMatch, knownKeys: Record<string, boolean> = {}): ToJson<Api.ArrayOfMatch> {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiArrayOfMatchKeys.forEach(k => knownKeys[k] = true)
	
	const result: ToJson<Api.ArrayOfMatch> = {
		'date': allowUndefined(dateToJson)(`${name}.date`, value['date']),
		'numberOfMatches': allowUndefined(integerToJson)(`${name}.numberOfMatches`, value['numberOfMatches']),
	}

	return result
}

export function modelApiArrayOfMatchFromJson(name: string, value: any): Api.ArrayOfMatch {
	const knownKeys: Record<string, boolean> = {}
	const result: Api.ArrayOfMatch = modelApiArrayOfMatchFromJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.ArrayOfMatch: ${key}`)
		}
	}

	return result
}

export function modelApiArrayOfMatchToJson(name: string, value: Api.ArrayOfMatch): ToJson<Api.ArrayOfMatch> {
	const knownKeys: Record<string, boolean> = {}
	const result: ToJson<Api.ArrayOfMatch> = modelApiArrayOfMatchToJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.ArrayOfMatch: ${key}`)
		}
	}

	return result
}

const ApiArrayOfPokemonKeys: string[] = ['id', 'numberOfMatchs']

function modelApiArrayOfPokemonFromJsonContent(name: string, value: any, knownKeys: Record<string, boolean> = {}): Api.ArrayOfPokemon {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiArrayOfPokemonKeys.forEach(k => knownKeys[k] = true)

	const result: Api.ArrayOfPokemon = {
		'id': allowUndefined(integerFromJson)(`${name}.id`, value['id']),
		'numberOfMatchs': allowUndefined(integerFromJson)(`${name}.numberOfMatchs`, value['numberOfMatchs']),
	}

	return result
}

function modelApiArrayOfPokemonToJsonContent(name: string, value: Api.ArrayOfPokemon, knownKeys: Record<string, boolean> = {}): ToJson<Api.ArrayOfPokemon> {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiArrayOfPokemonKeys.forEach(k => knownKeys[k] = true)
	
	const result: ToJson<Api.ArrayOfPokemon> = {
		'id': allowUndefined(integerToJson)(`${name}.id`, value['id']),
		'numberOfMatchs': allowUndefined(integerToJson)(`${name}.numberOfMatchs`, value['numberOfMatchs']),
	}

	return result
}

export function modelApiArrayOfPokemonFromJson(name: string, value: any): Api.ArrayOfPokemon {
	const knownKeys: Record<string, boolean> = {}
	const result: Api.ArrayOfPokemon = modelApiArrayOfPokemonFromJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.ArrayOfPokemon: ${key}`)
		}
	}

	return result
}

export function modelApiArrayOfPokemonToJson(name: string, value: Api.ArrayOfPokemon): ToJson<Api.ArrayOfPokemon> {
	const knownKeys: Record<string, boolean> = {}
	const result: ToJson<Api.ArrayOfPokemon> = modelApiArrayOfPokemonToJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.ArrayOfPokemon: ${key}`)
		}
	}

	return result
}

const ApiGetNumberOfMatchsByPokemon200ResponseKeys: string[] = ['id', 'numberOfMatchs']

function modelApiGetNumberOfMatchsByPokemon200ResponseFromJsonContent(name: string, value: any, knownKeys: Record<string, boolean> = {}): Api.GetNumberOfMatchsByPokemon200Response {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiGetNumberOfMatchsByPokemon200ResponseKeys.forEach(k => knownKeys[k] = true)

	const result: Api.GetNumberOfMatchsByPokemon200Response = {
		'id': allowUndefined(integerFromJson)(`${name}.id`, value['id']),
		'numberOfMatchs': allowUndefined(integerFromJson)(`${name}.numberOfMatchs`, value['numberOfMatchs']),
	}

	return result
}

function modelApiGetNumberOfMatchsByPokemon200ResponseToJsonContent(name: string, value: Api.GetNumberOfMatchsByPokemon200Response, knownKeys: Record<string, boolean> = {}): ToJson<Api.GetNumberOfMatchsByPokemon200Response> {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiGetNumberOfMatchsByPokemon200ResponseKeys.forEach(k => knownKeys[k] = true)
	
	const result: ToJson<Api.GetNumberOfMatchsByPokemon200Response> = {
		'id': allowUndefined(integerToJson)(`${name}.id`, value['id']),
		'numberOfMatchs': allowUndefined(integerToJson)(`${name}.numberOfMatchs`, value['numberOfMatchs']),
	}

	return result
}

export function modelApiGetNumberOfMatchsByPokemon200ResponseFromJson(name: string, value: any): Api.GetNumberOfMatchsByPokemon200Response {
	const knownKeys: Record<string, boolean> = {}
	const result: Api.GetNumberOfMatchsByPokemon200Response = modelApiGetNumberOfMatchsByPokemon200ResponseFromJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.GetNumberOfMatchsByPokemon200Response: ${key}`)
		}
	}

	return result
}

export function modelApiGetNumberOfMatchsByPokemon200ResponseToJson(name: string, value: Api.GetNumberOfMatchsByPokemon200Response): ToJson<Api.GetNumberOfMatchsByPokemon200Response> {
	const knownKeys: Record<string, boolean> = {}
	const result: ToJson<Api.GetNumberOfMatchsByPokemon200Response> = modelApiGetNumberOfMatchsByPokemon200ResponseToJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.GetNumberOfMatchsByPokemon200Response: ${key}`)
		}
	}

	return result
}

const ApiGetNumberOfVictoriesByPokemon200ResponseKeys: string[] = ['id', 'numberOfVictories']

function modelApiGetNumberOfVictoriesByPokemon200ResponseFromJsonContent(name: string, value: any, knownKeys: Record<string, boolean> = {}): Api.GetNumberOfVictoriesByPokemon200Response {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiGetNumberOfVictoriesByPokemon200ResponseKeys.forEach(k => knownKeys[k] = true)

	const result: Api.GetNumberOfVictoriesByPokemon200Response = {
		'id': allowUndefined(integerFromJson)(`${name}.id`, value['id']),
		'numberOfVictories': allowUndefined(integerFromJson)(`${name}.numberOfVictories`, value['numberOfVictories']),
	}

	return result
}

function modelApiGetNumberOfVictoriesByPokemon200ResponseToJsonContent(name: string, value: Api.GetNumberOfVictoriesByPokemon200Response, knownKeys: Record<string, boolean> = {}): ToJson<Api.GetNumberOfVictoriesByPokemon200Response> {
	if (typeof value !== 'object' || value === undefined || value === null) {
		throw `Invalid type for ${name}: expected object got ${typeof value}`
	}

	ApiGetNumberOfVictoriesByPokemon200ResponseKeys.forEach(k => knownKeys[k] = true)
	
	const result: ToJson<Api.GetNumberOfVictoriesByPokemon200Response> = {
		'id': allowUndefined(integerToJson)(`${name}.id`, value['id']),
		'numberOfVictories': allowUndefined(integerToJson)(`${name}.numberOfVictories`, value['numberOfVictories']),
	}

	return result
}

export function modelApiGetNumberOfVictoriesByPokemon200ResponseFromJson(name: string, value: any): Api.GetNumberOfVictoriesByPokemon200Response {
	const knownKeys: Record<string, boolean> = {}
	const result: Api.GetNumberOfVictoriesByPokemon200Response = modelApiGetNumberOfVictoriesByPokemon200ResponseFromJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.GetNumberOfVictoriesByPokemon200Response: ${key}`)
		}
	}

	return result
}

export function modelApiGetNumberOfVictoriesByPokemon200ResponseToJson(name: string, value: Api.GetNumberOfVictoriesByPokemon200Response): ToJson<Api.GetNumberOfVictoriesByPokemon200Response> {
	const knownKeys: Record<string, boolean> = {}
	const result: ToJson<Api.GetNumberOfVictoriesByPokemon200Response> = modelApiGetNumberOfVictoriesByPokemon200ResponseToJsonContent(name, value, knownKeys)

	/* Known keys */
	// TODO if we don't ignore unknown properties
	for (const key of Object.keys(value)) {
		if (!knownKeys[key]) {
			// throw `Unexpected key: ${key}`
			console.warn(`Unexpected key in Api.GetNumberOfVictoriesByPokemon200Response: ${key}`)
		}
	}

	return result
}
