openapi: 3.0.1
info:
  title: User service
  description: "Because we need users"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: https://127.0.0.1:33d33
tags:
  - name: user
    description: users informations and manipulations
paths:
  /users:
    get:
      tags:
        - user
      summary: List of all users
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfUsers"
  
components:
  schemas:
    ArrayOfUsers:
      title: Array of users
      description: array of users
      type: array
      items:
        type: object
        properties:
          id:
            description: id of the user
            type: integer
            format: int64
            minimum: 0
          username:
            description: name of the user
            type: string
            format: text
          statut: 
            description: status of the user
            type: boolean
          score:
            description: score of the player
            type: integer
            format: number
          password:
            description: password of the user
            type: string
            format: text
   
