/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import passport from 'passport'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.MatchApi) {
	app.get(
		'/matchs/count-a-day-last-30-days',
		function (req, res) {
			try {
				impl.getMatchsAdayLast30Days().then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.arrayToJson(v.modelApiArrayOfMatchToJson)('response', response.body)
						} catch (error) {
							console.error('Invalid response body in match.getMatchsAdayLast30Days', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}

					console.log('Unsupported response in match.getMatchsAdayLast30Days', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in match.getMatchsAdayLast30Days', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

}
