/* eslint-disable */
// tslint:disable
/**
 * Stats service
 * Because we need statistics
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface MatchApi {
	getMatchsAdayLast30Days: () => Promise<GetMatchsAdayLast30DaysResponse>
}

export type GetMatchsAdayLast30DaysResponse = GetMatchsAdayLast30Days200Response

export interface GetMatchsAdayLast30Days200Response {
	status: 200
	body: Api.ArrayOfMatch[]
	headers?: never
}

